FROM ubuntu:latest
MAINTAINER Louy Heidar (Louy.Heidar@QA.com)


RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y  software-properties-common && \
    add-apt-repository ppa:webupd8team/java -y && \
    apt-get update && \
echo oracle-java7-installer images/javainstall select true | /usr/bin/debconf-s$
    apt-get install -y oracle-java8-installer && \
    apt-get clean

