FROM ubuntu:latest
MAINTAINER Louy Heidar (Louy.Heidar@QA.com)


  save        Save one or more images to a tar archive (streamed to STDOUT by default)
  tag         Create a tag TARGET_IMAGE that refers to SOURCE_IMAGE

Run 'docker image COMMAND --help' for more information on a command.
ubuntu@ip-172-31-10-242:~/images$ sudo docker images
REPOSITORY          TAG                 IMAGE ID            CREATED              SIZE
ubuntu              latest              b28403d120c9        About a minute ago   118MB

