version : '2'

services:
  php:
   image: php:latest
   ports:
     - "80:80"
   volumes:
     - /home/ubuntu/sharedvolume:/var/lib/shared

  db:
   image: mysql:latest
   ports:
     - "3306:3306"
   volumes:
     - /home/ubuntu/sharedvolume:/var/lib/shared
   environment:
     MYSQL_ROOT_PASSWORD: testpass

  jk:
   image: jenkins:latest
   ports:
     - "8080:8080"
